name: Build, Scan, and Push Docker Image to ACR

on:
  push:
    branches:
      - main
      - naga-kishore-patch
    paths:
      - 'appointment/**'
      - 'Dockerfile'
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  acr_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Container Registry Build
        uses: Azure/acr-build@v1
        with:
          service_principal: ${{ secrets.AZURE_CLIENT_ID }}
          service_principal_password: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant: ${{ secrets.AZURE_TENANT_ID }}
          registry: acrhclwesteurope          # ACR name without .azurecr.io
          repository: appointment-service
          git_access_token: ${{ secrets.GITHUB_TOKEN }}
          image: appointment-service     # repository name
          tag: ${{ github.sha }}         # commit SHA
          folder: appointment            # folder where your Dockerfile and service.js are
          dockerfile: Dockerfile         # optional, defaults to Dockerfile in the folder
          build_args: |
            NODE_ENV=production

      - name: Scan Docker image
        uses: aquasecurity/trivy-action@v2
        with:
          image-ref: youracrname.azurecr.io/appointment-service:${{ github.sha }}
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH
